openapi: 3.2.0
info:
  title: Paperless Parts Events API
  description: The Paperless Parts API provides access to your data, enabling developers to easily integrate Paperless Parts with third-party systems, such as Customer Relationship Management (CRM) and Enterprise Resource Planning (ERP) tools.
  version: '1.0'
  termsOfService: https://www.paperlessparts.com/web-service-agreement/
  contact:
    name: Paperless Parts
    url: https://www.paperlessparts.com
    email: support@paperlessparts.com
servers:
- url: '{url}/{version}'
  variables:
    url:
      default: https://api.paperlessparts.com
    version:
      default: v1
security:
- app_id: []
tags:
- name: Events
  description: Endpoints for viewing communications between Paperless Parts and ERP integrations
paths:
  /events/public:
    get:
      summary: Returns a list of events
      description: Returns a list of events. Use the ID provided from the event to create integration actions
      operationId: ListEvents
      parameters:
      - in: query
        name: event_type_in
        schema:
          type: string
        required: false
        description: Filter to return events of a specified event type
      - in: query
        name: was_dispatched
        schema:
          type: string
        required: false
        description: Filter to return only events that have associated dispatch records
      tags:
      - Events
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
  /managed_integrations/public/{managed_integration_uuid}/poll:
    get:
      summary: Returns a list of new events
      description: Returns a list of events that have not yet been dispatched for the managed integration.
      operationId: PollEvents
      parameters:
      - in: path
        name: managed_integration_uuid
        schema:
          type: string
        required: true
        description: The unique identifier for the managed integration whose events you want to poll
      - in: query
        name: create_dispatch_records
        schema:
          type: string
        required: false
        description: Whether you would like to create associated dispatch records for all events returned for this page. If set to true (or left unspecified), the events returned will not show up in the next response from this endpoint.
      - in: query
        name: event_type_in
        schema:
          type: string
        required: false
        description: Filter to return events of a specified event type
      - in: query
        name: was_dispatched
        schema:
          type: string
        required: false
        description: Filter to return only events that have associated dispatch records
      tags:
      - Events
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
components:
  schemas:
    Event:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
        type:
          type: string
          example: integration_action.requested
          description: The event type
        data:
          type: object
          description: Data relevant to the event
        related_object:
          type:
          - string
          - 'null'
          format: uuid
        related_object_type:
          type: string
        created:
          type: string
          readOnly: true
          example: '2020-08-25T18:00:53+00:00'
  securitySchemes:
    app_id:
      type: apiKey
      description: API key to authorize requests.
      name: Authorization
      in: header
