openapi: 3.2.0
info:
  title: Paperless Parts API v2 Processes API
  description: The Paperless Parts API provides access to your data, enabling developers to easily integrate Paperless Parts with third-party systems, such as Customer Relationship Management (CRM) and Enterprise Resource Planning (ERP) tools.
  version: '2.0'
  termsOfService: https://www.paperlessparts.com/web-service-agreement/
  contact:
    name: Paperless Parts
    url: https://www.paperlessparts.com
    email: support@paperlessparts.com
servers:
- url: '{url}/{version}'
  variables:
    url:
      default: https://api.paperlessparts.com
    version:
      default: v2
security:
- app_id: []
tags:
- name: Processes
  description: Endpoints for managing Processes, Operation Definitions, and Add on Definitions
paths:
  /processes/public/processes:
    get:
      summary: Get a list of Processes
      description: A complete list of Processes.
      operationId: ProcessesList
      tags:
      - Processes
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    uuid:
                      type: string
                      example: 3ec5051e-9d2d-4ea4-b903-abd9b6aa3448
                      description: The Processes' uuid
                    name:
                      type: string
                      example: CNC Machining
                      description: The name of the Process
                    external_name:
                      type: string
                      example: CNC Machining
                      description: The external name of the Process
        404:
          description: Not found response
          content:
            text/plain:
              schema:
                title: No Processes found
                type: string
                example: 'Error: Not Found'
  /processes/public/operation_definitions:
    get:
      summary: Get a list of Operation Defintions
      description: A complete list of Operation Defintions.
      operationId: OperationDefintionList
      tags:
      - Processes
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    uuid:
                      type: string
                      example: 3ec5051e-9d2d-4ea4-b903-abd9b6aa3448
                      description: The Operation Definition's uuid
                    erp_code:
                      type:
                      - string
                      - 'null'
                    name:
                      type: string
                      example: Assemble
                      description: The name of the Process
                    is_outside_service:
                      type: boolean
                    metadata:
                      $ref: '#/components/schemas/Metadata'
        404:
          description: Not found response
          content:
            text/plain:
              schema:
                title: No Operation Definitions found
                type: string
                example: 'Error: Not Found'
  /processes/public/discount_definitions:
    get:
      summary: Get a list of Discount definitions
      description: A complete list of Discount defintions.
      operationId: DiscountDefinitionList
      tags:
      - Processes
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    uuid:
                      type: string
                      example: 44887c8d-6321-415d-b806-574a2e35afe3
                      description: The Discount definition's UUID
                    name:
                      type: string
                      example: Good Customer Discount
                      description: The name of the Discount definition
        404:
          description: Not found response
          content:
            text/plain:
              schema:
                title: No Discount Definitions found
                type: string
                example: 'Error: Not Found'
  /processes/public/add_on_definitions:
    get:
      summary: Get a list of Add On Definitions
      description: A complete list of Add On Definitions.
      operationId: AddOnDefinitionList
      tags:
      - Processes
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 4
                      description: The Add On Defintion's id
                    erp_code:
                      type:
                      - string
                      - 'null'
                    name:
                      type: string
                      example: Assemble
                      description: The name of the Process
        404:
          description: Not found response
          content:
            text/plain:
              schema:
                title: No Add On Definitions found
                type: string
                example: 'Error: Not Found'
  /processes/public/materials:
    get:
      summary: Get a list of Materials
      description: Returns a list of supplier materials. The materials are returned 20 results at a time and can be iterated over by using the page parameter.
      operationId: ListMaterials
      parameters:
      - in: query
        name: search
        schema:
          type: string
        required: false
        description: Value used to search against the material name
      - in: query
        name: page
        schema:
          type: string
        required: false
        description: The page of results to return.
      - in: query
        name: material_family
        schema:
          type: string
        required: false
        description: The material family name.
      - in: query
        name: material_class
        schema:
          type: string
        required: false
        description: The material class name.
      - in: query
        name: material_name
        schema:
          type: string
        required: false
        description: The material name.
      tags:
      - Processes
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    description: The total number of records matching the supplied query parameters
                  next:
                    type:
                    - string
                    - 'null'
                    description: The URL of the next page of results. Null if this is the last page
                  previous:
                    type:
                    - string
                    - 'null'
                    description: The URL of the previous page of results. Null if this is the first page
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        uuid:
                          type: string
                          example: 3ec5051e-9d2d-4ea4-b903-abd9b6aa3448
                          description: The Material's uuid
                        name:
                          type: string
                          example: Aluminum 6061
                          description: The name of the Material
                        custom_name:
                          type:
                          - string
                          - 'null'
                          example: Aluminum 6061
                          description: The custom name of the material
                        material_family:
                          type: string
                          example: Aluminum
                          description: The Material's family
                        material_class:
                          type: string
                          example: Metal
                          description: The Material's Class
        404:
          description: Not found response
          content:
            text/plain:
              schema:
                title: No Materials found
                type: string
                example: 'Error: Not Found'
components:
  schemas:
    Metadata:
      type: object
      example: '{ crm_id: 1581 }'
      description: Object that can be used to attach key-value data to an object. Up to 25 keys can be speficied, with key names up to 40 characters long and values up to 500 characters long.
  securitySchemes:
    app_id:
      type: apiKey
      description: API key to authorize requests.
      name: Authorization
      in: header
